ignore:
  - "autohbw/.*"
  - "examples/autohbw*"
  - "examples/*example*"
  - "examples/memkind*"
  - "src/tbb_wrapper.c"
  - "test/.*"
  - "utils/**/*"

coverage:
  range: "60...100"
  status:
    project:
      default:
        informational: true
        threshold: 100%
        target: 0%
    patch:
      default:
        informational: true
        threshold: 100%
        target: 0%

comment: false
